(TeX-add-style-hook
 "sampling-and-monte-carlo-integration"
 (lambda ()
   (LaTeX-add-labels
    "ex:importance-sampling-to-estimate-tail-probabilities"
    "ex:monte-carlo-integration-and-importance-sampling"
    "eq:cauchy-pdf"
    "fig:gauss-cauchy-logpdf"
    "ex:ex1"
    "ex:sampling-from-a-Laplace-distribution"
    "fig:Fx"
    "ex:rejection-sampling"
    "q:basic-mcmc"
    "sfig:density"
    "sfig:scatter"
    "fig:mcmc_approx"
    "eq:gauss-prop"
    "qpt:mh"
    "qpt:mh_test"
    "sfig:00"
    "sfig:77"
    "fig:initial"
    "q:poisson-reg"
    "fig:easy"
    "q:mh_mixing"
    "qpt:mh_trace"
    "sfig:traceplot_many_good"
    "sfig:traceplot_many_small"
    "sfig:traceplot_many_big"
    "fig:traceplots"))
 :latex)

